### ISSUE TITLE
Explore prometheus metrics for monitoring support activity

### ISSUE THREAD

**Issue by brenton** [gregsheremeta/proactive-support-bot#28]
We'd like to have grafana dashboards that report support activity.  The cluster support service likely has access to all the data we need.  Potential dashboards include:

- Support clusters failing upgrades or alerting that no one is yet investigating
- Clusters with the most support activity (recent comments in EBS, number of cases open, etc)

**Comment by brenton** [comment]
The goal would be to have the telemeter service configured to scrap the cluster support service (they're running in the same OpenShift cluster).

It would likely also be wise to add general stats metrics to the service for monitoring the service itself.

**Comment by brenton** [comment]
I think we could have a number of interesting metrics that could be used to measure the level of proactive support activity

- gauge for the number of open support cases for a cluster
- counter for the number of times a cluster has been commented on (could be used to determine how active a given cluster's investigation is)
- counter for the number of times a cluster ID has been referenced in any message in the proactive-support channel

**Comment by sferich888** [comment]
@brenton we can get the number of 'proactive' support clusters by searching SFDC / Hydra (and looking for a 'tag') @TheDiemer and I are working with the Hydra team on an API to do this now. 

If we can also query for cases, by a cluster ID: https://projects.engineering.redhat.com/browse/CPSTRATA-1048
