### ISSUE TITLE
There should be some way to assign clusters to someone in engineering

### ISSUE THREAD

**Issue by brenton** [gregsheremeta/proactive-support-bot#30]
Before we have a case with a support engineer assigned there are plenty of situations where we need to assign a cluster to someone in engineering for review.  We should have a queue where this data is stored.  Jira would be one place it could live but it could be as simple as a spreadsheet obviously.  The UI could be something along the lines of `@cluster-support assign <uuid>` and `@cluster-support assign <user> <uuid>`.

**Comment by brenton** [comment]
It's important to note that whether or not a cluster is assigned should also be exposed via a metric label.  We want to be able to create grafana dashboards with metrics on assigned and unassigned clusters.

**Comment by wking** [comment]
@brenton sketched a possible implementation:

* On bot startup and periodically thereafter, poll Jira (or whatever the store is) to get the set of assigned clusters.
* Update that set dynamically as the bot processes commands.

The post-startup polls would guard against things like "someone touched Jira directly to unassign a dev from that cluster".
